/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface HighlightRange {
  start: number
  end: number
}

export declare function initializeLogging(development: boolean, callback: (entry: NativeLogEntry) => void): void

export declare function initializeSearch(): Promise<void>

export interface NativeLogEntry {
  level: string
  target: string
  message: string
}

export declare function readAppIcon(path: string): Promise<Buffer | null>

export declare function recordUsage(id: string): void

export declare function search(query: string, development?: boolean | undefined | null): Promise<Array<SearchHit>>

export interface SearchHit {
  id: string
  recencyKey: string
  title: string
  provider: string
  label: string
  score: number
  ranges: Array<HighlightRange>
  actionType: string
  actionValue: string
}

export declare function toggleSystemTheme(): Promise<boolean>
