/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class ClipboardHistory {
  static open(directory: string, onChange: () => void): Promise<ClipboardHistory>
  startMonitoring(): void
  stopMonitoring(): void
  list(options: ClipboardListOptions): Promise<Array<ClipboardItem>>
  get(id: string): Promise<ClipboardItem | null>
  readText(id: string): Promise<string>
  readImage(id: string): Promise<Buffer>
  addText(text: string): Promise<ClipboardItem>
  copy(id: string): Promise<void>
  setFavorite(id: string, favorite: boolean): Promise<boolean>
  categories(): Promise<Array<ClipboardCategory>>
  saveCategory(name: string, color: string, id?: string | undefined | null): Promise<ClipboardCategory>
  deleteCategory(id: string): Promise<void>
  setRemark(id: string, remark: string): Promise<void>
  setCategory(id: string, categoryId?: string | undefined | null): Promise<void>
  editText(id: string, text: string): Promise<ClipboardItem>
  delete(id: string): Promise<boolean>
  clearHistory(): Promise<number>
}

export interface ClipboardCategory {
  id: string
  name: string
  color: string
}

export interface ClipboardItem {
  id: string
  kind: string
  imagePath?: string
  text?: string
  paths: Array<string>
  width?: number
  height?: number
  createdAt: number
  lastUsedAt: number
  useCount: number
  favorite: boolean
  remark?: string
  categoryId?: string
}

export interface ClipboardListOptions {
  query?: string
  favoritesOnly?: boolean
  kind?: string
  categoryId?: string
  limit?: number
  offset?: number
}

export declare function initializeLogging(development: boolean, callback: (entry: NativeLogEntry) => void): void

export interface NativeLogEntry {
  level: string
  target: string
  message: string
  file?: string
  line?: number
}
