[package]
name = "xw-platform"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
objc2 = "0.6"
objc2-app-kit = { version = "0.3", features = [
    "NSWorkspace",
    "NSRunningApplication",
    "NSImage",
    "NSImageRep",
    "NSBitmapImageRep",
] }
objc2-foundation = { version = "0.3", features = ["NSString", "NSFileManager"] }
