export * from "./gen/testing/fixture_pb.ts";
export * from "./gen/xiaowei/app_pb.ts";
export * from "./gen/xiaowei/clipboard_pb.ts";
export * from "./gen/xiaowei/common_pb.ts";
export * from "./gen/xiaowei/kv_pb.ts";
export * from "./gen/xiaowei/launcher_pb.ts";
export * from "./gen/xiaowei/search_pb.ts";
export * from "./gen/xiaowei/settings_pb.ts";
export * from "./gen/xiaowei/system_pb.ts";
