/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Agent {
  static create(): Agent
  static open(root: string): Promise<Agent>
  createGatewayEndpoint(): GatewayEndpoint
  close(): Promise<void>
}

export declare class GatewayEndpoint {
  manifest(): string
  bind(callback: (control: string, payload: Buffer) => Promise<Buffer | string>, context: string): void
  activate(): Promise<Buffer | string>
  dispatchLocal(route: string, payload: Buffer, context: string): Promise<Buffer | string>
  streamControl(control: string, payload: Buffer, context: string): Promise<Buffer | string>
  subscribeLocal(id: string, event: string, filter: Buffer | undefined | null, context: string): Promise<Buffer | string>
  unsubscribeLocal(id: string): void
  deliver(id: string, payload: Buffer): Promise<Buffer | string>
  close(): Promise<Buffer | string>
}

export declare function initializeLogging(development: boolean, callback: (entry: NativeLogEntry) => void): void

export interface NativeLogEntry {
  level: string
  target: string
  message: string
  file?: string
  line?: number
}
